set dateformat dmy --- para establecer el formato de fecha

## -- Primera Actualización: Eliminar salto de línea de cada campo especificado
UPDATE [dbo].[Temp_HDI_SEGUROS_Base_AUTOS_ETL]
SET 
    [codigo_plan_negocio_especial] = REPLACE(REPLACE(REPLACE([codigo_plan_negocio_especial], CHAR(9), ''), CHAR(10), ''), CHAR(13), ''),
    [cod_sucursal] = REPLACE(REPLACE(REPLACE([cod_sucursal], CHAR(9), ''), CHAR(10), ''), CHAR(13), ''),
    [cod_ramo] = REPLACE(REPLACE(REPLACE([cod_ramo], CHAR(9), ''), CHAR(10), ''), CHAR(13), ''),
    [ramo] = REPLACE(REPLACE(REPLACE([ramo], CHAR(9), ''), CHAR(10), ''), CHAR(13), ''),
    [poliza] = REPLACE(REPLACE(REPLACE([poliza], CHAR(9), ''), CHAR(10), ''), CHAR(13), ''),
    [certificado] = REPLACE(REPLACE(REPLACE([certificado], CHAR(9), ''), CHAR(10), ''), CHAR(13), ''),
    [fecha_inicio_poliza] = REPLACE(REPLACE(REPLACE([fecha_inicio_poliza], CHAR(9), ''), CHAR(10), ''), CHAR(13), ''),
    [fecha_fin_poliza] = REPLACE(REPLACE(REPLACE([fecha_fin_poliza], CHAR(9), ''), CHAR(10), ''), CHAR(13), ''),
    [nro_identificacion_tomador] = REPLACE(REPLACE(REPLACE([nro_identificacion_tomador], CHAR(9), ''), CHAR(10), ''), CHAR(13), ''),
    [nombre_tomador] = REPLACE(REPLACE(REPLACE([nombre_tomador], CHAR(9), ''), CHAR(10), ''), CHAR(13), ''),
    [nro_identificacion_asegurado] = REPLACE(REPLACE(REPLACE([nro_identificacion_asegurado], CHAR(9), ''), CHAR(10), ''), CHAR(13), ''),
    [nombre_asegurado] = REPLACE(REPLACE(REPLACE([nombre_asegurado], CHAR(9), ''), CHAR(10), ''), CHAR(13), ''),
    [amparo_garantia] = REPLACE(REPLACE(REPLACE([amparo_garantia], CHAR(9), ''), CHAR(10), ''), CHAR(13), ''),
    [descripcion_amparo_garantia] = REPLACE(REPLACE(REPLACE([descripcion_amparo_garantia], CHAR(9), ''), CHAR(10), ''), CHAR(13), ''),
    [direccion_riesgo] = REPLACE(REPLACE(REPLACE([direccion_riesgo], CHAR(9), ''), CHAR(10), ''), CHAR(13), ''),
    [departamento_riesgo] = REPLACE(REPLACE(REPLACE([departamento_riesgo], CHAR(9), ''), CHAR(10), ''), CHAR(13), ''),
    [ciudad_riesgo] = REPLACE(REPLACE(REPLACE([ciudad_riesgo], CHAR(9), ''), CHAR(10), ''), CHAR(13), ''),
    [intermediario] = REPLACE(REPLACE(REPLACE([intermediario], CHAR(9), ''), CHAR(10), ''), CHAR(13), '');



## -- Segunda Actualización: -- Este script eliminará los caracteres especiales

UPDATE [dbo].[Temp_HDI_SEGUROS_Base_AUTOS_ETL]
SET
 [codigo_plan_negocio_especial] = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE([codigo_plan_negocio_especial], CHAR(39), ''), CHAR(34), ''), CHAR(33), ''), ',', ''),   '&', ''), '/', ''), '*', ''), '+', ''), '[', ''), ']', ''), '\\', ''), '¡', ''), '!', ''), '¿', ''), '?', ''), '$', ''), '#', ''), '%', ''), '|', ''), '°', ''), '{', ''), '}', ''), '´', ''), '(', ''), ')', ''),
[cod_sucursal] = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE([cod_sucursal], CHAR(39), ''), CHAR(34), ''), CHAR(33), ''), ',', ''),   '&', ''), '/', ''), '*', ''), '+', ''), '[', ''), ']', ''), '\\', ''), '¡', ''), '!', ''), '¿', ''), '?', ''), '$', ''), '#', ''), '%', ''), '|', ''), '°', ''), '{', ''), '}', ''), '´', ''), '(', ''), ')', ''),
[cod_ramo] = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE([cod_ramo], CHAR(39), ''), CHAR(34), ''), CHAR(33), ''), ',', ''),   '&', ''), '/', ''), '*', ''), '+', ''), '[', ''), ']', ''), '\\', ''), '¡', ''), '!', ''), '¿', ''), '?', ''), '$', ''), '#', ''), '%', ''), '|', ''), '°', ''), '{', ''), '}', ''), '´', ''), '(', ''), ')', ''),
[ramo] = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE([ramo], CHAR(39), ''), CHAR(34), ''), CHAR(33), ''), ',', ''),   '&', ''), '/', ''), '*', ''), '+', ''), '[', ''), ']', ''), '\\', ''), '¡', ''), '!', ''), '¿', ''), '?', ''), '$', ''), '#', ''), '%', ''), '|', ''), '°', ''), '{', ''), '}', ''), '´', ''), '(', ''), ')', ''),
[poliza] = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE([poliza], CHAR(39), ''), CHAR(34), ''), CHAR(33), ''), ',', ''),   '&', ''), '/', ''), '*', ''), '+', ''), '[', ''), ']', ''), '\\', ''), '¡', ''), '!', ''), '¿', ''), '?', ''), '$', ''), '#', ''), '%', ''), '|', ''), '°', ''), '{', ''), '}', ''), '´', ''), '(', ''), ')', ''),
[certificado] = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE([certificado], CHAR(39), ''), CHAR(34), ''), CHAR(33), ''), ',', ''),   '&', ''), '/', ''), '*', ''), '+', ''), '[', ''), ']', ''), '\\', ''), '¡', ''), '!', ''), '¿', ''), '?', ''), '$', ''), '#', ''), '%', ''), '|', ''), '°', ''), '{', ''), '}', ''), '´', ''), '(', ''), ')', ''),
[fecha_inicio_poliza] = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE([fecha_inicio_poliza], CHAR(39), ''), CHAR(34), ''), CHAR(33), ''), ',', ''),   '&', ''), '/', ''), '*', ''), '+', ''), '[', ''), ']', ''), '\\', ''), '¡', ''), '!', ''), '¿', ''), '?', ''), '$', ''), '#', ''), '%', ''), '|', ''), '°', ''), '{', ''), '}', ''), '´', ''), '(', ''), ')', ''),
[fecha_fin_poliza] = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE([fecha_fin_poliza], CHAR(39), ''), CHAR(34), ''), CHAR(33), ''), ',', ''),   '&', ''), '/', ''), '*', ''), '+', ''), '[', ''), ']', ''), '\\', ''), '¡', ''), '!', ''), '¿', ''), '?', ''), '$', ''), '#', ''), '%', ''), '|', ''), '°', ''), '{', ''), '}', ''), '´', ''), '(', ''), ')', ''),
[nro_identificacion_tomador] = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE([nro_identificacion_tomador], CHAR(39), ''), CHAR(34), ''), CHAR(33), ''), ',', ''),  '&', ''), '/', ''), '*', ''), '+', ''), '[', ''), ']', ''), '\\', ''), '¡', ''), '!', ''), '¿', ''), '?', ''), '$', ''), '#', ''), '%', ''), '|', ''), '°', ''), '{', ''), '}', ''), '´', ''), '(', ''), ')', ''),
[nombre_tomador] = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE([nombre_tomador], CHAR(39), ''), CHAR(34), ''), CHAR(33), ''), ',', ''),  '&', ''), '/', ''), '*', ''), '+', ''), '[', ''), ']', ''), '\\', ''), '¡', ''), '!', ''), '¿', ''), '?', ''), '$', ''), '#', ''), '%', ''), '|', ''), '°', ''), '{', ''), '}', ''), '´', ''), '(', ''), ')', ''),
[nro_identificacion_asegurado] = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE([nro_identificacion_asegurado], CHAR(39), ''), CHAR(34), ''), CHAR(33), ''), ',', ''),  '&', ''), '/', ''), '*', ''), '+', ''), '[', ''), ']', ''), '\\', ''), '¡', ''), '!', ''), '¿', ''), '?', ''), '$', ''), '#', ''), '%', ''), '|', ''), '°', ''), '{', ''), '}', ''), '´', ''), '(', ''), ')', ''),
[nombre_asegurado] = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE([nombre_asegurado], CHAR(39), ''), CHAR(34), ''), CHAR(33), ''), ',', ''),  '&', ''), '/', ''), '*', ''), '+', ''), '[', ''), ']', ''), '\\', ''), '¡', ''), '!', ''), '¿', ''), '?', ''), '$', ''), '#', ''), '%', ''), '|', ''), '°', ''), '{', ''), '}', ''), '´', ''), '(', ''), ')', ''),
[amparo_garantia] = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE([amparo_garantia], CHAR(39), ''), CHAR(34), ''), CHAR(33), ''), ',', ''),  '&', ''), '/', ''), '*', ''), '+', ''), '[', ''), ']', ''), '\\', ''), '¡', ''), '!', ''), '¿', ''), '?', ''), '$', ''), '#', ''), '%', ''), '|', ''), '°', ''), '{', ''), '}', ''), '´', ''), '(', ''), ')', ''),
[descripcion_amparo_garantia] = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE([descripcion_amparo_garantia], CHAR(39), ''), CHAR(34), ''), CHAR(33), ''), ',', ''),   '&', ''), '/', ''), '*', ''), '+', ''), '[', ''), ']', ''), '\\', ''), '¡', ''), '!', ''), '¿', ''), '?', ''), '$', ''), '#', ''), '%', ''), '|', ''), '°', ''), '{', ''), '}', ''), '´', ''), '(', ''), ')', ''),
[direccion_riesgo] = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE([direccion_riesgo], CHAR(39), ''), CHAR(34), ''), CHAR(33), ''), ',', ''),   '&', ''), '/', ''), '*', ''), '+', ''), '[', ''), ']', ''), '\\', ''), '¡', ''), '!', ''), '¿', ''), '?', ''), '$', ''), '#', ''), '%', ''), '|', ''), '°', ''), '{', ''), '}', ''), '´', ''), '(', ''), ')', ''),
[departamento_riesgo] = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE([departamento_riesgo], CHAR(39), ''), CHAR(34), ''), CHAR(33), ''), ',', ''),  '&', ''), '/', ''), '*', ''), '+', ''), '[', ''), ']', ''), '\\', ''), '¡', ''), '!', ''), '¿', ''), '?', ''), '$', ''), '#', ''), '%', ''), '|', ''), '°', ''), '{', ''), '}', ''), '´', ''), '(', ''), ')', ''),
[ciudad_riesgo] = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE([ciudad_riesgo], CHAR(39), ''), CHAR(34), ''), CHAR(33), ''), ',', ''),   '&', ''), '/', ''), '*', ''), '+', ''), '[', ''), ']', ''), '\\', ''), '¡', ''), '!', ''), '¿', ''), '?', ''), '$', ''), '#', ''), '%', ''), '|', ''), '°', ''), '{', ''), '}', ''), '´', ''), '(', ''), ')', ''),
[intermediario] = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE([intermediario], CHAR(39), ''), CHAR(34), ''), CHAR(33), ''), ',', ''),  '&', ''), '/', ''), '*', ''), '+', ''), '[', ''), ']', ''), '\\', ''), '¡', ''), '!', ''), '¿', ''), '?', ''), '$', ''), '#', ''), '%', ''), '|', ''), '°', ''), '{', ''), '}', ''), '´', ''), '(', ''), ')', '');
